const questions=[
{week:1,num:1,title:"Fruit counter",desc:"Sita wants to count the number of fruits she has: apples, bananas, and cherries. Declare variables to store these quantities and print each with an appropriate message.\n\n• apples (integer): stores number of apples, 10\n• bananas (integer): stores number of bananas, 20\n• cherries (integer): stores number of cherries, 30",
inputFmt:"No console input.",
outputFmt:"Line 1: \"Number of apples is <apples>\"\nLine 2: \"Number of bananas is <bananas>\"\nLine 3: \"Number of cherries is <cherries>\"",
hint:"Use integer variables and f-strings: print(f'Number of apples is {apple}')",
tests:[{input:"",expected:"Number of apples is 10\nNumber of bananas is 20\nNumber of cherries is 30"}],
solution:`apple = 10\nbanana = 20\ncherries = 30\nprint(f"Number of apples is {apple}")\nprint(f"Number of bananas is {banana}")\nprint(f"Number of cherries is {cherries}")`},

{week:1,num:2,title:"Personal details",desc:"Alice wants to share her personal details: name, age, and city of residence. Declare variables to store this information and print each detail on a new line with a descriptive message.\n\n• name (string): stores Alice's name, \"Alice\"\n• age (integer): stores Alice's age, 25\n• city (string): stores Alice's city, \"Delhi\"",
inputFmt:"No console input.",
outputFmt:"Line 1: \"Name is <name>\"\nLine 2: \"Age is <age>\"\nLine 3: \"City is <city>\"",
hint:"Use string and int variables: name='Alice', age=25, city='Delhi'",
tests:[{input:"",expected:"Name is Alice\nAge is 25\nCity is Delhi"}],
solution:`name = "Alice"\nage = 25\ncity = "Delhi"\nprint(f"Name is {name}")\nprint(f"Age is {age}")\nprint(f"City is {city}")`},

{week:1,num:3,title:"Boolean statuses",desc:"John's user profile tracks three boolean statuses: whether the user is active, an admin, and verified. Declare boolean variables to store these statuses and print each status with a descriptive message.\n\n• is_active (boolean): True\n• is_admin (boolean): False\n• is_verified (boolean): True",
inputFmt:"No console input.",
outputFmt:"Line 1: \"User active status is <is_active>\"\nLine 2: \"User admin status is <is_admin>\"\nLine 3: \"User verified status is <is_verified>\"",
hint:"In Python booleans are True/False (capital). Use f-strings to print them.",
tests:[{input:"",expected:"User active status is True\nUser admin status is False\nUser verified status is True"}],
solution:`is_active = True\nis_admin = False\nis_verified = True\nprint(f"User active status is {is_active}")\nprint(f"User admin status is {is_admin}")\nprint(f"User verified status is {is_verified}")`},

{week:1,num:4,title:"Triangle classifier",desc:"Fazil needs a triangle classification program. Given the lengths of the sides of a triangle (side1, side2, and side3), determine whether the triangle is Equilateral, Isosceles, or Scalene.\n\n• If all sides are equal → Equilateral\n• If exactly two sides are equal → Isosceles\n• If all sides are different → Scalene",
inputFmt:"Line 1: float A (first side)\nLine 2: float B (second side)\nLine 3: float C (third side)",
outputFmt:"\"The triangle is classified as X\" where X is Equilateral, Isosceles, or Scalene.",
hint:"Check: if A==B==C → Equilateral; elif A==B or B==C or A==C → Isosceles; else Scalene",
tests:[{input:"90.0\n90.0\n90.0",expected:"The triangle is classified as Equilateral"},{input:"4.5\n4.5\n6.8",expected:"The triangle is classified as Isosceles"},{input:"12.3\n15.7\n17.8",expected:"The triangle is classified as Scalene"}],
solution:`A = float(input())\nB = float(input())\nC = float(input())\nif A==B and B==C:\n    print("The triangle is classified as Equilateral")\nelif A==B or B==C or A==C:\n    print("The triangle is classified as Isosceles")\nelse:\n    print("The triangle is classified as Scalene")`},

{week:1,num:5,title:"Zodiac sign",desc:"Banu is an astrologer who wants to determine zodiac signs based on birthdates.\n\nZodiac Sign Ranges:\n• Aries: March 21 – April 19\n• Taurus: April 20 – May 20\n• Gemini: May 21 – June 20\n• Cancer: June 21 – July 22\n• Leo: July 23 – August 22\n• Other: For dates outside of the above ranges",
inputFmt:"Line 1: integer representing the day of birth (1–31)\nLine 2: string representing the month of birth",
outputFmt:"\"Your zodiac sign is <sign>\"",
hint:"Check month and day ranges: Aries = March 21–April 19, Taurus = April 20–May 20, etc.",
tests:[{input:"15\nApril",expected:"Your zodiac sign is Aries"},{input:"2\nMay",expected:"Your zodiac sign is Taurus"},{input:"21\nJune",expected:"Your zodiac sign is Cancer"},{input:"30\nJuly",expected:"Your zodiac sign is Leo"},{input:"23\nSeptember",expected:"Your zodiac sign is Other"}],
solution:`date = int(input())\nmonth = input()\nif (month=="March" and date>=21) or (month=="April" and date<=19):\n    print("Your zodiac sign is Aries")\nelif (month=="April" and date>=20) or (month=="May" and date<=20):\n    print("Your zodiac sign is Taurus")\nelif (month=="May" and date>=21) or (month=="June" and date<=20):\n    print("Your zodiac sign is Gemini")\nelif (month=="June" and date>=21) or (month=="July" and date<=22):\n    print("Your zodiac sign is Cancer")\nelif (month=="July" and date>=23) or (month=="August" and date<=22):\n    print("Your zodiac sign is Leo")\nelse:\n    print("Your zodiac sign is Other")`},

{week:2,num:1,title:"Digital root",desc:"Alice works at a digital marketing company where she analyzes large datasets. She needs to calculate the digital root of customer ID numbers. The digital root is obtained by repeatedly summing the digits of a number until a single digit remains.\n\nExample: 98675 → 9+8+6+7+5 = 35 → 3+5 = 8\n\nFunction prototype: def digital_root(num)",
inputFmt:"A single integer num.",
outputFmt:"An integer representing the sum of digits until a single digit is obtained.",
hint:"Use a while loop: while num > 9, sum its digits, then repeat.",
tests:[{input:"451110",expected:"3"},{input:"1234",expected:"1"},{input:"98675",expected:"8"}],
solution:`def digital_root(num):\n    s=0\n    while num:\n        s+=num%10\n        num//=10\n        if s>9 and num==0:\n            num=s\n            s=0\n    return s\nprint(digital_root(int(input())))`},

{week:2,num:2,title:"Sum of digits",desc:"Sophia is developing a feature for her online banking application that calculates the total sum of digits in customers' account numbers. This sum is used to generate unique verification codes for secure transactions.\n\nFunction Specification: def sum_digits(num)",
inputFmt:"A single integer representing the customer's account number.",
outputFmt:"An integer representing the sum of the digits of the account number.",
hint:"Loop: extract last digit with num%10, add to sum, then num//=10.",
tests:[{input:"123245",expected:"17"},{input:"0",expected:"0"}],
solution:`def sum_digits(num):\n    s=0\n    while num:\n        s+=num%10\n        num//=10\n    return s\nprint(sum_digits(int(input())))`},

{week:2,num:3,title:"Net salary",desc:"Sophia manages payroll at a local business where employees are paid based on monthly hours worked. She needs to calculate the monthly salary considering a fixed hourly rate and standard deductions of 15% of the gross salary.\n\nCalculation:\n• gross = hours × rate\n• deductions = gross × 0.15\n• net = gross − deductions",
inputFmt:"Line 1: positive float — number of hours worked\nLine 2: positive float — hourly rate",
outputFmt:"Line 1: \"Hours Worked: {hours:.2f} hours\"\nLine 2: \"Hourly Rate: {rate:.2f} per hour\"\nLine 3: \"Net Salary: {salary:.2f}\"",
hint:"gross = hours * rate; deductions = gross * 0.15; net = gross - deductions. Format to 2 decimal places.",
tests:[{input:"40.00\n12.50",expected:"Hours Worked: 40.00 hours\nHourly Rate: 12.50 per hour\nNet Salary: 425.00"},{input:"80.00\n30.75",expected:"Hours Worked: 80.00 hours\nHourly Rate: 30.75 per hour\nNet Salary: 2091.00"}],
solution:`hours=float(input())\nrate=float(input())\ngross=hours*rate\nnet=gross*0.85\nprint(f"Hours Worked: {hours:.2f} hours")\nprint(f"Hourly Rate: {rate:.2f} per hour")\nprint(f"Net Salary: {net:.2f}")`},

{week:2,num:4,title:"Sales tax",desc:"Sarah works at a retail store and needs a program to calculate the total price after adding sales tax. The store applies a fixed sales tax rate of 8% (0.08), defined as a global constant.\n\nFunction Signature: total_cost(item_cost)",
inputFmt:"A single positive floating-point number representing the cost of the item.",
outputFmt:"Line 1: \"Item Cost: {cost:.2f}\"\nLine 2: \"Sales Tax Rate: 8.0%\"\nLine 3: \"Total Cost: {total:.2f}\"",
hint:"total = item_cost * 1.08. Use f-strings with :.2f formatting.",
tests:[{input:"50.00",expected:"Item Cost: 50.00\nSales Tax Rate: 8.0%\nTotal Cost: 54.00"},{input:"100.5",expected:"Item Cost: 100.50\nSales Tax Rate: 8.0%\nTotal Cost: 108.54"}],
solution:`cost=float(input())\ntotal=cost*1.08\nprint(f"Item Cost: {cost:.2f}")\nprint("Sales Tax Rate: 8.0%")\nprint(f"Total Cost: {total:.2f}")`},

{week:2,num:5,title:"Count vowels",desc:"Arjun is building a text analyzer for his English assignment. He needs to create a function that counts how many vowels (a, e, i, o, u — both lowercase and uppercase) are present in a given string.\n\nFunction Signature: count_vowels(input_string)",
inputFmt:"A single line containing a string.",
outputFmt:"\"Number of vowels in the string: [count]\"",
hint:"Loop through each character and check if it's in 'aeiouAEIOU'.",
tests:[{input:"Hello, World!",expected:"Number of vowels in the string: 3"},{input:"Python is a great programming language.",expected:"Number of vowels in the string: 12"},{input:"APPle",expected:"Number of vowels in the string: 2"}],
solution:`def count_vowels(s):\n    return sum(1 for c in s if c in 'aeiouAEIOU')\nprint("Number of vowels in the string:", count_vowels(input()))`},

{week:3,num:1,title:"Replace characters",desc:"Sarah is a technical writer who needs to format two documents. Both contain a placeholder character that needs to be replaced with another character. She wants both modified documents printed in a single line, separated by a space.",
inputFmt:"Line 1: string1 (first document)\nLine 2: string2 (second document)\nLine 3: char1 (placeholder to replace)\nLine 4: char2 (replacement character)",
outputFmt:"A single line containing modified string1 and string2 separated by a space.",
hint:"Use str.replace(old, new) on both strings, then print with a space between.",
tests:[{input:"Hello\nWorld\no\na",expected:"Hella Warld"},{input:"12345\n45123\n1\n0",expected:"02345 45023"}],
solution:`s1=input()\ns2=input()\nc1=input()\nc2=input()\nprint(s1.replace(c1,c2), s2.replace(c1,c2))`},

{week:3,num:2,title:"Email generator",desc:"John Smith is a new employee at company \"iamNeo\" with the role of admin. Generate an email address using the convention: first letter of first name + last name + domain.\n\n• Admins get: @admin.company.com\n• Other roles get: @company.com",
inputFmt:"Line 1: first_name (string)\nLine 2: last_name (string)\nLine 3: role (string)\nLine 4: company (string)",
outputFmt:"The generated email address: first_letter_of_firstname + lastname + domain",
hint:"name = firstname[0].lower() + lastname.lower(). Check if role == 'admin' for the domain.",
tests:[{input:"John\nSmith\nadmin\niamNeo",expected:"jsmith@admin.iamneo.com"},{input:"Anne\nCuthbert\nIT\niamNeo",expected:"acuthbert@iamneo.com"}],
solution:`fn=input()\nln=input()\nrole=input()\nco=input()\nname=fn[0].lower()+ln.lower()\nif role=="admin":\n    print(f"{name}@{role}.{co.lower()}.com")\nelse:\n    print(f"{name}@{co.lower()}.com")`},

{week:3,num:3,title:"Alternating chars",desc:"Rekha needs to combine two strings by alternating their characters. She has two strings str1 and str2, both of equal length. Create a new string where characters alternate: str1[0]+str2[0]+str1[1]+str2[1]+...",
inputFmt:"Line 1: string str1\nLine 2: string str2 (same length as str1)",
outputFmt:"The concatenated string in alternating character format.",
hint:"Loop with range(len(str1)), concatenate str1[i]+str2[i] each iteration.",
tests:[{input:"abc\ndef",expected:"adbecf"},{input:"140401\n------",expected:"1-4-0-4-0-1-"}],
solution:`s1=input()\ns2=input()\nresult=''.join(s1[i]+s2[i] for i in range(len(s1)))\nprint(result)`},

{week:3,num:4,title:"Reverse & concat",desc:"Ram wants to create a program that takes two strings as input, reverses the second string, and then concatenates it with the first string.",
inputFmt:"Line 1: first string\nLine 2: second string",
outputFmt:"A string: first string + reversed second string.",
hint:"Use string slicing: str2[::-1] reverses a string in Python.",
tests:[{input:"hello\nword",expected:"hellodrow"},{input:"ram@123\nmailid",expected:"ram@123diliam"}],
solution:`s1=input()\ns2=input()\nprint(s1+s2[::-1])`},

{week:3,num:5,title:"Valid area codes",desc:"Ravi is designing a contact list parser that processes phone numbers in (XXX) XXX-XXXX format. Extract valid area codes.\n\nA phone number is valid only if:\n• Format: (XXX) XXX-XXXX\n• All X positions are digits only\n• Total length is exactly 14 characters",
inputFmt:"Line 1: integer n (number of phone numbers)\nNext n lines: one phone number string each",
outputFmt:"\"Valid area codes: \" followed by comma-separated area codes from valid numbers.",
hint:"Check: s[0]='(' s[4]=')' s[5]=' ', digits at [1:4], [6:9], [10:14]. Length must be 14.",
tests:[{input:"3\n(123) 456-7890\n(abc) 111-2222\n(987) 654-3210",expected:"Valid area codes: 123,987"},{input:"3\n(000) 000-0000\n(999) 999-9999\n(123 456-7890",expected:"Valid area codes: 000,999"}],
solution:`n=int(input())\nvalid=[]\nfor _ in range(n):\n    s=input()\n    if len(s)==14 and s[0]=='(' and s[4]==')' and s[5]==' ' and s[1:4].isdigit() and s[6:9].isdigit() and s[10:14].isdigit():\n        valid.append(s[1:4])\nprint("Valid area codes: "+",".join(valid))`},

{week:4,num:1,title:"First n primes",desc:"Tom wants to create a dictionary that lists the first n prime numbers, where each key represents the position of the prime number, and the value is the prime number itself.",
inputFmt:"A single integer n — the number of prime numbers to generate.",
outputFmt:"A dictionary where each key is an integer from 1 to n, and the value is the corresponding prime number.\nExample: {1: 2, 2: 3, 3: 5, 4: 7}",
hint:"Check primality by testing divisibility from 2 to num-1. Build dict as {1:2, 2:3, ...}",
tests:[{input:"4",expected:"{1: 2, 2: 3, 3: 5, 4: 7}"}],
solution:`n=int(input())\nd={}\nnum=2\ncount=1\nwhile count<=n:\n    if all(num%i!=0 for i in range(2,num)):\n        d[count]=num\n        count+=1\n    num+=1\nprint(d)`},

{week:4,num:2,title:"Merge expense dicts",desc:"Arjun is a financial analyst managing quarterly expense reports from two departments — Marketing and Operations. He needs to combine both reports into a single consolidated summary.\n\n• For common categories: add the values together\n• For unique categories: retain as-is\n• Keys appear in order they are first encountered",
inputFmt:"Line 1: integer n (pairs in dict1)\nNext 2n lines: key-value pairs for dict1\nNext line: integer m (pairs in dict2)\nNext 2m lines: key-value pairs for dict2",
outputFmt:"\"Combined Dictionary: {key1: value1, key2: value2, ...}\"",
hint:"Start with dict1, then for each key in dict2: if key exists, add values; else insert new key.",
tests:[{input:"2\nhardware\n1000\nmaintenance\n700\n3\nmaintenance\n300\nstationery\n200\ntravel\n500",expected:"Combined Dictionary: {'hardware': 1000, 'maintenance': 1000, 'stationery': 200, 'travel': 500}"}],
solution:`n=int(input())\nd={}\nfor _ in range(n):\n    k=input();v=int(input())\n    d[k]=v\nm=int(input())\nfor _ in range(m):\n    k=input();v=int(input())\n    d[k]=d.get(k,0)+v\nprint(f"Combined Dictionary: {d}")`},

{week:4,num:3,title:"Min/max order IDs",desc:"Alex manages an online store and needs to analyze customer orders. He wants to identify the smallest and largest order amounts and their corresponding order IDs.",
inputFmt:"Line 1: integer n (number of orders)\nNext 2n lines: alternating order ID (int) and order amount (int)",
outputFmt:"Line 1: \"Smallest Order ID: {id},\"\nLine 2: \"Largest Order ID: {id}\"",
hint:"Track min_amount and max_amount as you read each order.",
tests:[{input:"5\n101\n200\n102\n3000\n103\n100\n104\n20\n105\n500",expected:"Smallest Order ID: 104,\nLargest Order ID: 102"}],
solution:`n=int(input())\nmin_id=max_id=0\nmi=float('inf');mx=float('-inf')\nfor _ in range(n):\n    oid=int(input());amt=int(input())\n    if amt<mi:mi=amt;min_id=oid\n    if amt>mx:mx=amt;max_id=oid\nprint(f"Smallest Order ID: {min_id},")\nprint(f"Largest Order ID: {max_id}")`},

{week:4,num:4,title:"Warehouse boxes",desc:"At a warehouse, two delivery trucks bring boxes daily. Each truck reports boxes delivered to each section. Compute the element-wise sum and output as a tuple.",
inputFmt:"Line 1: integer n (number of sections)\nLine 2: n integers separated by commas (truck 1)\nLine 3: n integers separated by commas (truck 2)",
outputFmt:"A tuple of integers representing total boxes per section.\nExample: (5, 15, 17, 10, 15)",
hint:"Read both lines, split by comma, zip them together and sum each pair.",
tests:[{input:"5\n3, 8, 12, 4, 6\n2, 7, 5, 6, 9",expected:"(5, 15, 17, 10, 15)"},{input:"3\n0, 20, 10\n5, 15, 25",expected:"(5, 35, 35)"}],
solution:`n=int(input())\na=list(map(int,input().split(',')))\nb=list(map(int,input().split(',')))\nresult=tuple(a[i]+b[i] for i in range(n))\nprint(result)`},

{week:4,num:5,title:"Tuple concat string",desc:"Teju is exploring tuples and their manipulation. She is given a task to transform a list of integers into a tuple and concatenate its elements into a single string.",
inputFmt:"Line 1: integer n (number of elements)\nNext n lines: one integer per line",
outputFmt:"Line 1: tuple in format (element1, element2, ...)\nLine 2: concatenation of all elements as a string",
hint:"Build tuple with +=, build string with str(val). Print both on separate lines.",
tests:[{input:"3\n1\n20\n3",expected:"(1, 20, 3)\n1203"},{input:"5\n10\n20\n40\n5\n70",expected:"(10, 20, 40, 5, 70)\n102040570"}],
solution:`n=int(input())\nt=();s=''\nfor _ in range(n):\n    v=int(input())\n    t+=(v,);s+=str(v)\nprint(t)\nprint(s)`},

{week:5,num:1,title:"BMI calculator",desc:"A health organization is conducting a Health Check-Up Camp. Develop a program that records participants' details and calculates their BMI.\n\nClass Person methods:\n• bmi(): calculates BMI = weight / height²\n• __str__(): returns string representation of the person",
inputFmt:"Line 1: number of people\nFor each person: name (str), age (int), gender (str), height in meters (float), weight in kg (float)",
outputFmt:"\"Name: <name>, Age: <age>, Gender: <gender>, Height: <height> m, Weight: <weight> kg, BMI: <bmi>\"",
hint:"BMI = weight / height². Round to 2 decimal places.",
tests:[{input:"1\nAlice\n30\nFemale\n1.8\n75",expected:"Name: Alice, Age: 30, Gender: Female, Height: 1.8 m, Weight: 75.0 kg, BMI: 23.15"}],
solution:`class Person:\n    def __init__(self,n,a,g,h,w):\n        self.n=n;self.a=a;self.g=g;self.h=h;self.w=w\n    def bmi(self):\n        return round(self.w/self.h**2,2)\n    def __str__(self):\n        return f"Name: {self.n}, Age: {self.a}, Gender: {self.g}, Height: {self.h} m, Weight: {self.w} kg, BMI: {self.bmi()}"\ncount=int(input())\nfor _ in range(count):\n    n=input();a=int(input());g=input();h=float(input());w=float(input())\n    print(Person(n,a,g,h,w))`},

{week:5,num:2,title:"Money addition",desc:"A banking system allows customers to store money in rupees and paisa. When paisa sum exceeds 100, it needs to be converted into rupees. Implement using a class and objects.\n\nClass Money with method add(self, other) to add two amounts.",
inputFmt:"Line 1: two integers — rupees and paisa for first amount\nLine 2: two integers — rupees and paisa for second amount",
outputFmt:"The total sum rounded to two decimal places (e.g. 93.50)",
hint:"Sum paisa. If >= 100, add paisa//100 to rupees and take paisa%100.",
tests:[{input:"50 85\n42 65",expected:"93.50"},{input:"254 45\n845 65",expected:"1100.10"},{input:"54 25\n35 75",expected:"90.00"}],
solution:`r1,p1=map(int,input().split())\nr2,p2=map(int,input().split())\nr=r1+r2;p=p1+p2\nif p>=100:\n    r+=p//100;p%=100\nprint(f"{r}.{p:02d}")`},

{week:5,num:3,title:"Count digits",desc:"A digital security firm analyzes numeric codes. Each time a user enters a code, the system must determine how many digits it contains.\n\nClass DigitsOpr with methods:\n• getNum(self): accepts a positive integer\n• countDigits(self): counts and returns the number of digits",
inputFmt:"A single positive integer N.",
outputFmt:"An integer representing the total number of digits in the input.",
hint:"Repeatedly do num//10 until num becomes 0, counting iterations.",
tests:[{input:"12345",expected:"5"},{input:"2",expected:"1"}],
solution:`class DigitsOpr:\n    def countDigits(self,n):\n        count=0\n        while n:\n            n//=10;count+=1\n        return count\nobj=DigitsOpr()\nprint(obj.countDigits(int(input())))`},

{week:5,num:4,title:"Vowel or consonant",desc:"A language learning app helps users understand vowels and consonants. Users enter a single alphabet and the system classifies it.\n\nClass CharacterChecker with method:\n• checkVowelOrConsonant(self, char): checks if vowel or consonant",
inputFmt:"A single alphabet character (uppercase or lowercase).",
outputFmt:"\"The character '<char>' is a consonant\" or \"The character '<char>' is a vowel\"",
hint:"Check if char.lower() is in 'aeiou'. Print with the char in single quotes.",
tests:[{input:"j",expected:"The character 'j' is a consonant"},{input:"E",expected:"The character 'E' is a vowel"}],
solution:`c=input()\nif c.lower() in 'aeiou':\n    print(f"The character '{c}' is a vowel")\nelse:\n    print(f"The character '{c}' is a consonant")`}
];
